"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_macchiato"

format = """
[î‚¶](#c6a0f6)\
$os\
$username\
[î‚°](bg:#ed8796 fg:#c6a0f6)\
$directory\
[î‚°](fg:#ed8796 bg:#f5a97f)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[î‚°](fg:#f5a97f bg:#8bd5ca)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[î‚°](fg:#8bd5ca bg:#7dc4e4)\
$docker_context\
[î‚°](fg:#7dc4e4 bg:#8aadf4)\
$time\
[î‚° ](fg:#8aadf4)\
"""

# TODO: implement theme
[palettes.catppuccin_macchiato]
white = '#b8c0eu'

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#c6a0f6 fg:#494d64"
style_root = "bg:#c6a0f6 fg:#494d64"
format = '[$user ]($style)'
disabled = true

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#c6a0f6 fg:#494d64"
disabled = false # Disabled by default

# This is the default symbols table.
[os.symbols]
Alpine = "ğŸ”ï¸ "
Amazon = "ğŸ™‚ "
Android = "ğŸ¤– "
Arch = "ğŸ—ï¸ "
CentOS = "ğŸ’  "
Debian = "ğŸŒ€ "
DragonFly = "ğŸ‰ "
Emscripten = "ğŸ”— "
EndeavourOS = "ğŸš€ "
Fedora = "ğŸ© "
FreeBSD = "ğŸ˜ˆ "
Garuda = "ğŸ¦… "
Gentoo = "ğŸ—œï¸ "
HardenedBSD = "ğŸ›¡ï¸ "
Illumos = "ğŸ¦ "
Linux = "ğŸ§ "
Macos = "îœ‘ "
Manjaro = "ğŸ¥­ "
Mariner = "ğŸŒŠ "
MidnightBSD = "ğŸŒ˜ "
Mint = "ğŸŒ¿ "
NetBSD = "ğŸš© "
NixOS = "â„ï¸ "
OpenBSD = "ğŸ¡ "
openSUSE = "ğŸ¦ "
OracleLinux = "ğŸ¦´ "
Pop = "ğŸ­ "
Raspbian = "ğŸ“ "
Redhat = "ğŸ© "
RedHatEnterprise = "ğŸ© "
Redox = "ğŸ§ª "
Solus = "â›µ "
SUSE = "ğŸ¦ "
Ubuntu = "ğŸ¯ "
Unknown = "â“ "
Windows = "ğŸªŸ "

[directory]
home_symbol = "ï€• "
style = "bold bg:#ed8796 fg:#494d64"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
"github.com" = "ïˆ "
"Code" = "ï‘ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[c]
symbol = "î˜ "
style = "bg:#8bd5ca fg:#494d64"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#7dc4e4 fg:#494d64"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = "î‰µ "
style = "bg:#8bd5ca fg:#494d64"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#8bd5ca fg:#494d64"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï˜"
style = "bold bg:#f5a97f fg:#494d64"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bold bg:#f5a97f fg:#494d64"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#8bd5ca fg:#494d64"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#8bd5ca fg:#494d64"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#8bd5ca fg:#494d64"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#8bd5ca fg:#494d64"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#8bd5ca fg:#494d64"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ïš¤ "
style = "bg:#8bd5ca fg:#494d64"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨ "
style = "bg:#8bd5ca fg:#494d64"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "bg:#8bd5ca fg:#494d64"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#8aadf4 fg:#494d64"
format = '[ â™¥ $time ]($style)'
